name: all-approve
on:
  pull_request_review:
    types: [submitted]

jobs:
  review-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            if (context.payload.pull_request.labels.some(label => label.name === 'レビュー待ち')) {
              github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                name: 'レビュー待ち'
              });
            }

            if (reviews.every(review => review.state === 'APPROVED')){
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['レビュー済み']
              });
            }
